name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - run: sudo xcode-select -s /Applications/Xcode_26.4.app
      - run: swift --version
      - run: swift build -v
      - run: swift test -v
